<?php

/**
 * DO NOT EDIT THIS FILE. IT IS JUST AN EXAMPLE...
 *
 * The fields that already have a valid value are used on local or building environment.
 * In production environment, the value will be different for security reasons.
 */
return [

    'GANDI_MAIL_PASSWORD' => 'FILL_ONLY_IF_YOU_WANT_TO_SEND_REAL_EMAILS',

];
