<?php

/**
 * DO NOT EDIT THIS FILE. IT IS JUST AN EXAMPLE...
 *
 * The fields listed below are used to set up the production server from your local machine.
 */
return [

    'APP_KEY' => '',

    'PGSQL_PASSWORD' => '',

    'DEFAULT_ADMIN_PASSWORD' => '',

    'GANDI_MAIL_PASSWORD' => '',

    'GITHUB_PASSWORD' => '',

    'SSL_PRIVATE_KEY' => '',

    'SSL_CERTIFICATE' => '',

];
