VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Configure the box
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "PizzeriaDev"

  # Run the base provisioning script
  config.vm.provision "shell" do |s|
    environment = 'local'
    s.path = "./provision.sh"
    s.args = [environment]
  end

end
